import flourite from 'flourite'
import Prism from 'prismjs'
import 'prismjs/components/prism-markup.js'
import 'prismjs/components/prism-markup-templating.js'
import 'prismjs/components/prism-css.js'
import 'prismjs/components/prism-clike.js'
import 'prismjs/components/prism-javascript.js'
import 'prismjs/components/prism-typescript.js'
import 'prismjs/components/prism-python.js'
import 'prismjs/components/prism-bash.js'
import 'prismjs/components/prism-json.js'
import 'prismjs/components/prism-yaml.js'
import 'prismjs/components/prism-markdown.js'
import 'prismjs/components/prism-java.js'
import 'prismjs/components/prism-go.js'
import 'prismjs/components/prism-rust.js'
import 'prismjs/components/prism-sql.js'
import 'prismjs/components/prism-docker.js'
import 'prismjs/components/prism-graphql.js'
import 'prismjs/components/prism-regex.js'
import 'prismjs/components/prism-c.js'
import 'prismjs/components/prism-cpp.js'
import 'prismjs/components/prism-csharp.js'
import 'prismjs/components/prism-php.js'
import 'prismjs/components/prism-ruby.js'
import 'prismjs/components/prism-kotlin.js'
import 'prismjs/components/prism-swift.js'
import 'prismjs/components/prism-dart.js'
import 'prismjs/components/prism-elixir.js'
import 'prismjs/components/prism-clojure.js'
import 'prismjs/components/prism-lua.js'
import 'prismjs/components/prism-perl.js'
import 'prismjs/components/prism-powershell.js'
import 'prismjs/components/prism-shell-session.js'
import 'prismjs/components/prism-diff.js'
import 'prismjs/components/prism-ini.js'
import 'prismjs/components/prism-toml.js'
import 'prismjs/components/prism-xml-doc.js'
import 'prismjs/components/prism-jsx.js'
import 'prismjs/components/prism-tsx.js'

export function highlightCode(code: string, lang: string): string {
  const detected = lang === 'text' ? flourite(code).language.toLowerCase() : lang.toLowerCase()
  const language = Prism.languages[detected] ? detected : 'text'
  return Prism.highlight(code, Prism.languages[language] || Prism.languages.text, language)
}

export default Prism
